id: outburn
canonical: http://fhir.outburn.co.il/
version: 0.3.0
name: outburnImplementationGuide
title: outburn LTD Implementation Guide
status: draft
publisher: Kippi Bordowitz
contact:
  - name: Kippi Bordowitz
    telecom:
      - system: email
        value: amos@outburn.co.il
description: Implementation guide for outburn LTD FHIR
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Artifacts Summary: artifacts.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
